<?php
// This script and data application were generated by AppGini 5.93
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/items.php");
	include_once("{$currDir}/items_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('items');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout(function() { window.location = "index.php?signOut=1"; }, 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = 'items';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`items`.`id`" => "id",
		"`items`.`item`" => "item",
		"`items`.`code`" => "code",
		"`items`.`balance`" => "balance",
		"IF(    CHAR_LENGTH(`categories1`.`category`), CONCAT_WS('',   `categories1`.`category`), '') /* Category */" => "category",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`items`.`id`',
		2 => 2,
		3 => 3,
		4 => '`items`.`balance`',
		5 => '`categories1`.`category`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`items`.`id`" => "id",
		"`items`.`item`" => "item",
		"`items`.`code`" => "code",
		"`items`.`balance`" => "balance",
		"IF(    CHAR_LENGTH(`categories1`.`category`), CONCAT_WS('',   `categories1`.`category`), '') /* Category */" => "category",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`items`.`id`" => "ID",
		"`items`.`item`" => "Item",
		"`items`.`code`" => "Code",
		"`items`.`balance`" => "Balance",
		"IF(    CHAR_LENGTH(`categories1`.`category`), CONCAT_WS('',   `categories1`.`category`), '') /* Category */" => "Category",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`items`.`id`" => "id",
		"`items`.`item`" => "item",
		"`items`.`code`" => "code",
		"`items`.`balance`" => "balance",
		"IF(    CHAR_LENGTH(`categories1`.`category`), CONCAT_WS('',   `categories1`.`category`), '') /* Category */" => "category",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['category' => 'Category', ];

	$x->QueryFrom = "`items` LEFT JOIN `categories` as categories1 ON `categories1`.`id`=`items`.`category` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'items_view.php';
	$x->RedirectAfterInsert = 'items_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Items';
	$x->TableIcon = 'resources/table_icons/injection.png';
	$x->PrimaryKey = '`items`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Item', 'Code', 'Balance', 'Category', ];
	$x->ColFieldName = ['item', 'code', 'balance', 'category', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/items_templateTV.html';
	$x->SelectedTemplate = 'templates/items_templateTVS.html';
	$x->TemplateDV = 'templates/items_templateDV.html';
	$x->TemplateDVP = 'templates/items_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `items`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='items' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `items`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='items' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`items`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: items_init
	$render = true;
	if(function_exists('items_init')) {
		$args = [];
		$render = items_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: items_header
	$headerCode = '';
	if(function_exists('items_header')) {
		$args = [];
		$headerCode = items_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: items_footer
	$footerCode = '';
	if(function_exists('items_footer')) {
		$args = [];
		$footerCode = items_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
