<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/sections.php');
	include_once(__DIR__ . '/sections_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('sections');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'sections';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`sections`.`id`" => "id",
		"`sections`.`section`" => "section",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`sections`.`id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`sections`.`id`" => "id",
		"`sections`.`section`" => "section",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`sections`.`id`" => "ID",
		"`sections`.`section`" => "Section",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`sections`.`id`" => "id",
		"`sections`.`section`" => "section",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`sections` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'sections_view.php';
	$x->RedirectAfterInsert = 'sections_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Storage sections';
	$x->TableIcon = 'resources/table_icons/color_swatch.png';
	$x->PrimaryKey = '`sections`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Section', ];
	$x->ColFieldName = ['section', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/sections_templateTV.html';
	$x->SelectedTemplate = 'templates/sections_templateTVS.html';
	$x->TemplateDV = 'templates/sections_templateDV.html';
	$x->TemplateDVP = 'templates/sections_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: sections_init
	$render = true;
	if(function_exists('sections_init')) {
		$args = [];
		$render = sections_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: sections_header
	$headerCode = '';
	if(function_exists('sections_header')) {
		$args = [];
		$headerCode = sections_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: sections_footer
	$footerCode = '';
	if(function_exists('sections_footer')) {
		$args = [];
		$footerCode = sections_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
