<?php
// This script and data application were generated by AppGini 5.93
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/suppliers.php");
	include_once("{$currDir}/suppliers_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('suppliers');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout(function() { window.location = "index.php?signOut=1"; }, 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = 'suppliers';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`suppliers`.`id`" => "id",
		"`suppliers`.`supplier`" => "supplier",
		"`suppliers`.`email`" => "email",
		"`suppliers`.`phone`" => "phone",
		"`suppliers`.`contact_person`" => "contact_person",
		"`suppliers`.`country`" => "country",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`suppliers`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`suppliers`.`id`" => "id",
		"`suppliers`.`supplier`" => "supplier",
		"`suppliers`.`email`" => "email",
		"`suppliers`.`phone`" => "phone",
		"`suppliers`.`contact_person`" => "contact_person",
		"`suppliers`.`country`" => "country",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`suppliers`.`id`" => "ID",
		"`suppliers`.`supplier`" => "Supplier",
		"`suppliers`.`email`" => "Email",
		"`suppliers`.`phone`" => "Phone",
		"`suppliers`.`contact_person`" => "Contact person",
		"`suppliers`.`country`" => "Country",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`suppliers`.`id`" => "id",
		"`suppliers`.`supplier`" => "supplier",
		"`suppliers`.`email`" => "email",
		"`suppliers`.`phone`" => "phone",
		"`suppliers`.`contact_person`" => "contact_person",
		"`suppliers`.`country`" => "country",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`suppliers` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'suppliers_view.php';
	$x->RedirectAfterInsert = 'suppliers_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Suppliers';
	$x->TableIcon = 'resources/table_icons/administrator.png';
	$x->PrimaryKey = '`suppliers`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Supplier', 'Email', 'Phone', 'Contact person', 'Country', ];
	$x->ColFieldName = ['supplier', 'email', 'phone', 'contact_person', 'country', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/suppliers_templateTV.html';
	$x->SelectedTemplate = 'templates/suppliers_templateTVS.html';
	$x->TemplateDV = 'templates/suppliers_templateDV.html';
	$x->TemplateDVP = 'templates/suppliers_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `suppliers`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='suppliers' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `suppliers`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='suppliers' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`suppliers`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: suppliers_init
	$render = true;
	if(function_exists('suppliers_init')) {
		$args = [];
		$render = suppliers_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: suppliers_header
	$headerCode = '';
	if(function_exists('suppliers_header')) {
		$args = [];
		$headerCode = suppliers_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: suppliers_footer
	$footerCode = '';
	if(function_exists('suppliers_footer')) {
		$args = [];
		$footerCode = suppliers_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
